version: '3.8'
services:
  flask:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT:
      DNS1:
      DNS2:
      DNS3:
      DNS4:
    ports:
      - ${PORT:34403}:5000
    dns:
      - ${DNS1:'2606:4700:4700::1111'}
      - ${DNS2:'2606:4700:4700::1001'}
      - ${DNS3:1.1.1.1}
      - ${DNS4:1.0.0.1}
    container_name: rai_m3u_retriever
